language: php
sudo: false
dist: trusty

php:
  - '7.4'
  - '8.0'
  - '8.1'
  - '8.2'

before_script:
    - composer self-update
    - composer install --verbose --prefer-dist --no-interaction -o

script:
    - ./vendor/bin/phpunit -c ./tests/phpunit.xml.dist ./tests
    - ./vendor/bin/phpcs --encoding=utf-8 --extensions=php --standard=./tests/phpcs.xml -nsp ./

notifications:
    email: false
