language: php
sudo: false
dist: trusty

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly
  - hhvm

before_script:
    - composer self-update
    - composer install --verbose --prefer-dist --no-interaction -o

script:
    - ./vendor/bin/phpunit -c ./tests/phpunit.xml.dist ./tests
    - ./vendor/bin/phpcs --encoding=utf-8 --extensions=php --standard=./tests/phpcs.xml -nsp ./

notifications:
    email: false

matrix:
  allow_failures:
    - php: '5.5'
    - php: nightly
    - php: hhvm
    
