#!/usr/bin/env bash
set -e
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )/..

docker build -t "php-units-of-measure:dev" .
docker run -it --rm -v `pwd`:/project "php-units-of-measure:dev" bash
